name: Caclculaion application

on:
  pull_requests:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
       -uses: actions/checkout@v3
       -name: Set up Python 3.10
        uses: docker/setup-buildx-action@v3
        with
         python-version "3.10"
         -name: Test
          run : cd ./calc-CI-CD/sources && python -m unittest test_calc.py
